name: Runner Inspection
on:
  push:
jobs:
  inspect:
    runs-on: ubuntu-latest
    steps:
      - name: show Hostname
        run: whoami

      - name: Show Operating System
        run: uname -a

      - name: Show Current Directory
        run: pwd


